variable "root_account" {
  type = any
  description = <<-EOF
    When true, this module will be considered the root/master account. Conflicts
    will occur if more than one instantiation of this module is created with the
    same name. When not true, this field should contain the output of another
    instantiation of this module where the field *is* true (indicating that it
    is a subaccount of the root/master account). This variable controls the
    configuration generated by this module (root/master account vs subaccount).
  EOF
}

variable "name" {
  type = string
  description = <<-EOF
    Name of the account being managed. Ideally one word, short, lowercase.
  EOF
}

variable "environment" {
  type = string
  default = null
  description = <<-EOF
    Logical environment account lives in (e.g. sandbox, dev, preprod, prod).
  EOF
}

variable "email" {
  type = string
  description = <<-EOF
    Email address associated with the account.
  EOF
}

variable "region" {
  type = string
  description = <<-EOF
    Region for account.
  EOF
}

variable "domain" {
  type = string
  default = null
  description = <<-EOF
    Domain associated with this account. Typically for operator and developer
    facing interfaces. When not explictly configured, it will be generated using
    the name / environment and parent domain.
  EOF
}

variable "bootstrap" {
  type = string
  default = null
  description = <<-EOF
    Inline configuration to be added to the bootstrap file for each account.
    Primarily provided to implement support for minimal DNS bootstrapping of
    accounts without hard coding a particular approach into this module.
  EOF
}

variable "sections" {
  type = map(object({
    remote_states = list(string)
    crosslinked = bool
  }))
  default = {}
  description = <<-EOF
    A map of discrete terraform projects to be created within this account.
    Useful for segregating terraform configurations by lifecycle. For example,
    a section titled "foundation" can contain long-lived resources like VPCs
    and a section titled "environment" can contain the resources deployed into
    it.

    remote_states:
      an array of other section names in this account whose terraform outputs
      should be made accessible to this section via a remote state backend.

    crosslinked:
      boolean indicating if resources created in this section need to be
      linked to resources in other accounts. if true, additional configuration
      for this section will be generated in a folder entitled "crosslink".

    imports:
      a list of key/value pairs where the key is the name of a local variable
      that will be accessible within the section and the value is a path to a
      YAML file containing shared config.
  EOF
}
